FROM node:16.14.2 as builder
WORKDIR /build

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
RUN yarn

COPY . .
RUN yarn prod

FROM nginx:1.21.6-alpine
WORKDIR /
# 时区
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist/website/browser/ /usr/share/nginx/html/dist
EXPOSE 80
